version: "3.8"

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    env_file:
      - env.list
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - env.list
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config/:/mosquitto/config/:ro
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - "1883:1883"
  mqtt-to-kafka:
    build: .
    container_name: mqtt-to-kafka
    depends_on:
      - kafka
      - mosquitto
    env_file:
      - env.list

volumes:
  data: ~